version: '3.8'

services:
  api:
    build:
      context: ./Backend
      dockerfile: DockerFile
    container_name: restaurant_api
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Production
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - BunnyStorage__StorageZoneName=${BunnyStorage__StorageZoneName}
      - BunnyStorage__Region=${BunnyStorage__Region}
      - BunnyStorage__AccessKey=${BunnyStorage__AccessKey}
      - BunnyStorage__CdnBaseUrl=${BunnyStorage__CdnBaseUrl}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: restaurant_frontend
    ports:
      - "3000:80"
    depends_on:
      api:
        condition: service_healthy

  database:
    image: postgres:16-alpine
    container_name: restaurant_postgres_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pg_data: